/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
* File Name: io-const.inc
*
* Type: Definition
* 
* Title: Constant symbol definitions
*
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */

; ========================== DEFINITIONS =============================


; Port D line map for input/output
.equiv  red,    0
.equiv  amber,  1
.equiv  green,  2

.equiv  SW1,    6
.equiv  SW2,    7
.equiv  SW3,    13
