/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
* File Name: sys.inc
*
* Type: External Declartion
*
* Title: Subroutine and register declarations 
*
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */

; =================== SUBROUTINE DECLARATIONS ==========================

.extern SYS.SUB.CONFIG
.extern SYS.SUB.MANAGE
    
.extern SYS.SUB.pointer_increment
.extern SYS.SUB.service_increment
    
; ===================== REGISTER DECLARATIONS ========================
    
.extern SYS.REG.STAT
.extern SYS.REG.CallIndex
.extern SYS.REG.REQUEST_FIFO
.extern SYS.REG.REQUEST_BUFFER.pointer
.extern SYS.REG.REQUEST_BUFFER.service
.extern SYS.REG.REQUEST_BUFFER.gap
    
.extern SYS.w0
.extern SYS.w1
.extern SYS.w2
.extern SYS.w3
.extern SYS.w4
.extern SYS.w5
.extern SYS.w6
.extern SYS.w7
.extern SYS.w8
.extern SYS.w9
.extern SYS.w10
.extern SYS.w11
.extern SYS.w12
.extern SYS.w13
.extern SYS.w14
.extern SYS.w15
    
.extern SYS.REG.EventCounter
    
    
    